/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "notificaciones.h"

bool_t *enviarnotificacion_2_svc(AlertaGenerada *argp, struct svc_req *rqstp){

	static bool_t  result;

	printf("\n\n         ALERTA GENERADA        ");

	printf("\nN° habitacion: %d",argp->paciente.numHabitacion);

	printf("\nNombres y apellidos: %s %s",argp->paciente.nombres,argp->paciente.apellidos);

	printf("\nEdad: %s",argp->paciente.edad); 

	printf("\nHora de la alerta: %s",argp->paciente.hora); 

	printf("\nFecha de la alerta: %s",argp->paciente.fecha); 


	printf("\n\n***         Indicadores que generaron la alerta        ***\n");

	printf("\n      Nombre Indicador                              Valor\n");
	for(int i=0; i<5; i++){
		if (argp->indicadoresAlerta[i].valor!=0)
		{
			if (argp->indicadoresAlerta[i].valor > 0)
			{
				printf("-> %s                      %.2f\n",argp->indicadoresAlerta[i].indicador,argp->indicadoresAlerta[i].valor);

			}
			
		}
		
	}

	printf("%s\n", argp->mensaje);
	printf("\n Fecha de la alerta                   Hora de la alerta                    Puntuacion\n");
	for(int i=0; i<5; i++){

				printf("-> %s                      %s                           %d\n",argp->ultimasAlertas[i].fecha,argp->ultimasAlertas[i].hora,argp->ultimasAlertas[i].puntuacion);
		
	}


	return &result;
}