/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "notificaciones.h"

bool_t *
enviarnotificacion_2_svc(AlertaGenerada *argp, struct svc_req *rqstp)
{
	static bool_t  result;

	printf("\n         ALERTA GENERADA        ");

	printf("\nN° habitacion: %d        ",argp->paciente.numHabitacion);

	printf("\nNombres y apellidos: %s        ",argp->paciente.nombres);

	printf("\nEdad: %s Dias/Meses/Anios",argp->paciente.edad); 

	printf("\nHora de la alerta: %s      ",argp->paciente.hora); 

	printf("\nFecha de la alerta: %s  ",argp->paciente.fecha); 


	printf("\n         Indicadores que generaron la alerta        ");

	printf("\n Nombre Indicador       Valor");

	return &result;
}
