/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "notificaciones.h"

bool_t *
enviarnotificacion_2_svc(AlertaGenerada *argp, struct svc_req *rqstp)
{
	static bool_t  result;

	printf("\n         ALERTA GENERADA        ");

	printf("\nN° habitacion: %d        ",argp->paciente.numHabitacion);

	printf("\nNombres y apellidos: %s        ",argp->paciente.nombres);

	//printf("\nEdad: %d",argp->paciente.edad); // TODO CAMBIAR A FLOAT

	printf("\nHora de la alerta: %s      ",argp->paciente.hora); // TODO Hora sin registro

	printf("\nFecha de la alerta: %s  ",argp->paciente.fecha); // TODO Fecha sin registro

	return &result;
}
