/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ALERTAS_H_RPCGEN
#define _ALERTAS_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXNOM 30

struct Indicadores {
	float frecuenciaCardiaca;
	float frecuenciaRespiratoria;
	float presionArterialSistolica;
	float presionArterialDiastolica;
	float temperatura;
	float saturacionOxigeno;
};
typedef struct Indicadores Indicadores;

struct Paciente {
	char nombres[MAXNOM];
	char apellidos[MAXNOM];
	char edad[MAXNOM];
	int numHabitacion;
	Indicadores indicadores;
};
typedef struct Paciente Paciente;

#define gestion_alertas 0x20000001
#define gestion_alertas_version 1

#if defined(__STDC__) || defined(__cplusplus)
#define enviarIndicadores 1
extern  bool_t * enviarindicadores_1(Paciente *, CLIENT *);
extern  bool_t * enviarindicadores_1_svc(Paciente *, struct svc_req *);
extern int gestion_alertas_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define enviarIndicadores 1
extern  bool_t * enviarindicadores_1();
extern  bool_t * enviarindicadores_1_svc();
extern int gestion_alertas_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Indicadores (XDR *, Indicadores*);
extern  bool_t xdr_Paciente (XDR *, Paciente*);

#else /* K&R C */
extern bool_t xdr_Indicadores ();
extern bool_t xdr_Paciente ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_ALERTAS_H_RPCGEN */
