/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "notificaciones.h"

bool_t
xdr_InfoPaciente (XDR *xdrs, InfoPaciente *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->nombres, MAXMSJ,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->apellidos, MAXMSJ,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->edad, MAXMSJ,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->numHabitacion))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->hora, MAXMSJ,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->fecha, MAXMSJ,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_IndicadoresAlerta (XDR *xdrs, IndicadoresAlerta *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->indicador, MAXMSJ,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->valor))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_UltimasAlertas (XDR *xdrs, UltimasAlertas *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->fecha, MAXMSJ,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->hora, MAXMSJ,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->puntuacion))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AlertaGenerada (XDR *xdrs, AlertaGenerada *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_InfoPaciente (xdrs, &objp->paciente))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->indicadoresAlerta, 5,
		sizeof (IndicadoresAlerta), (xdrproc_t) xdr_IndicadoresAlerta))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->mensaje, MAXMSJ,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->ultimasAlertas, 5,
		sizeof (UltimasAlertas), (xdrproc_t) xdr_UltimasAlertas))
		 return FALSE;
	return TRUE;
}
