/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "alertas.h"
#include "notificaciones.h"

bool_t *
enviarindicadores_1_svc(Paciente *argp, struct svc_req *rqstp)
{
	static bool_t  result;

	CLIENT *clnt;
	bool_t  *result_1;
	AlertaGenerada  enviarnotificacion_2_arg;
    char * dirIpServidorNotificaciones="localhost";

#ifndef	DEBUG
	clnt = clnt_create (dirIpServidorNotificaciones, gestion_notificaciones, gestion_notificaiones_version, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (dirIpServidorNotificaciones);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = enviarnotificacion_2(&enviarnotificacion_2_arg, clnt);
	if (result_1 == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */

	return &result;
}
