/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "alertas.h"
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>




//funciones

void ingresarDatosPaciente(Paciente *paciente);
void comenzarLecturaSensores(Paciente *paciente);
void menu(Paciente *paciente);
void
gestion_alertas_1(char *host)
{
	CLIENT *clnt;
	bool_t  *result_1;
	Paciente  enviarindicadores_1_arg;
    
    
    menu(&enviarindicadores_1_arg); //TODO falta Enviar al servidor los indicadores


#ifndef	DEBUG
	clnt = clnt_create (host, gestion_alertas, gestion_alertas_version, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = enviarindicadores_1(&enviarindicadores_1_arg, clnt);
	if (result_1 == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}

void menu(Paciente *paciente){
	int opcion=0;
	do{
			
			printf("\n  ======MENU=====   \n");
			//opciones menu
			printf("1. Ingresar datos del paciente\n");
			printf("2. Comenzar lectura de los sensores");
			printf("3. Terminar");
			scanf("%d",&opcion); 	// leyendo opcion

			switch (opcion)
			{
			case 1: ingresarDatosPaciente(paciente); // pasar por referencia TODO
				break;
			case 2: comenzarLecturaSensores(paciente); // pasar por referencia TODO
				break;
			default: printf("Opcion no valida.\n por favor ingresar una opcion correcta\n");
			break;
				
			}

			system("CLS");

		
	}
	while(opcion!=3);

	}

void ingresarDatosPaciente(Paciente *paciente)
{
	system("CLS");
	printf("\n-- INGRESANDO DATOS DEL PACIENTE --\n");

	printf("\nNombres y Apellidos: ");
	scanf("%s",&paciente->nombres);

	printf("\nEdad: ");
	scanf("%s",&paciente->edad);

	printf("\nNumero Habitacion: ");
	scanf("%s",&paciente->numHabitacion);

}

void comenzarLecturaSensores(Paciente *paciente){
	srand48(getpid());
	while(1){
	 
		paciente->indicadores.presionArterialDiastolica=rand()%(110-40+1) + 40;
		paciente->indicadores.frecuenciaCardiaca=rand()%(200+1);
		paciente->indicadores.frecuenciaRespiratoria=rand()%(60+1);
	
		paciente->indicadores.presionArterialSistolica==rand()%(160-50+1) + 50;
		paciente->indicadores.saturacionOxigeno=rand()%(110-40+1) + 40;
		paciente->indicadores.temperatura=drand48()*(44-33)+33;// numero aleatorio entre 33 y 44
		sleep(5);
	} 
}





int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	gestion_alertas_1 (host);
exit (0);
}
